// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoRLMrtDrQ0oAgnKLkfDgUQ9U5orX3W-U',
    appId: '1:159676535760:web:8bc8e8eeefc060c4519fd5',
    messagingSenderId: '159676535760',
    projectId: 'project-demo-7d853',
    authDomain: 'project-demo-7d853.firebaseapp.com',
    storageBucket: 'project-demo-7d853.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANjHRPdDbIxqAtC6hEDeH5wYMy24-LSbQ',
    appId: '1:159676535760:android:9118ea711c3daa68519fd5',
    messagingSenderId: '159676535760',
    projectId: 'project-demo-7d853',
    storageBucket: 'project-demo-7d853.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9Qd2Cgbe6jB7nPe8i_3J7zYsxwTzt-9g',
    appId: '1:159676535760:ios:98b131a07d885b2b519fd5',
    messagingSenderId: '159676535760',
    projectId: 'project-demo-7d853',
    storageBucket: 'project-demo-7d853.appspot.com',
    iosClientId: '159676535760-pit4j9hbpcvc29h49003ra0npt6pdcl7.apps.googleusercontent.com',
    iosBundleId: 'com.example.demoProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9Qd2Cgbe6jB7nPe8i_3J7zYsxwTzt-9g',
    appId: '1:159676535760:ios:98b131a07d885b2b519fd5',
    messagingSenderId: '159676535760',
    projectId: 'project-demo-7d853',
    storageBucket: 'project-demo-7d853.appspot.com',
    iosClientId: '159676535760-pit4j9hbpcvc29h49003ra0npt6pdcl7.apps.googleusercontent.com',
    iosBundleId: 'com.example.demoProject',
  );
}
